player09 <- c('Alex Ovechkin', 'Evgeni Malkin', 'Pavel Datsyuk', 'Zach Parise', 'Sidney Crosby')
points09 <- c(110, 113, 97, 94, 103)
playoffs09 <- c('Yes', 'Yes', 'Yes', 'Yes', 'Yes')
division09 <- c(1, 2, 1, 1, 2)
conference09 <- c(2, 4, 2, 3, 4)
playoff_data09 <- data.frame(player09, points09, playoffs09, division09, conference09)
colnames(playoff_data09) <- c('Player', 'Points', 'Playoffs', 'Division', 'Conference')

player10 <- c('Henrik Sedin', 'Alex Ovechkin', 'Sidney Crosby', 'Steven Stamkos', 'Patrick Kane')
points10 <- c(112, 109, 109, 95, 88)
playoffs10 <- c('Yes', 'Yes', 'Yes', 'No', 'Yes')
division10 <- c(1, 1, 2, 4, 1)
conference10 <- c(3, 1, 4, 12, 2)
playoff_data10 <- data.frame(player10, points10, playoffs10, division10, conference10)
colnames(playoff_data10) <- c('Player', 'Points', 'Playoffs', 'Division', 'Conference')

player11 <- c('Corey Perry', 'Daniel Sedin', 'Martin St. Louis', 'Jonathan Toews', 'Ryan Kesler')
points11 <- c(98, 104, 99, 76, 73)
playoffs11 <- c('Yes', 'Yes', 'Yes', 'Yes', 'Yes')
division11 <- c(2, 1, 2, 3, 1)
conference11 <- c(4, 1, 5, 8, 1)
playoff_data11 <- data.frame(player11, points11, playoffs11, division11, conference11)
colnames(playoff_data11) <- c('Player', 'Points', 'Playoffs', 'Division', 'Conference')

player12 <- c('Evgeni Malkin', 'Steven Stamkos', 'Claude Giroux', 'Jason Spezza', 'Erik Karlsson')
points12 <- c(109, 97, 93, 84, 78)
playoffs12 <- c('Yes', 'No', 'Yes', 'Yes', 'Yes')
division12 <- c(2, 3, 3, 2, 2)
conference12 <- c(4, 10, 5, 8, 8)
playoff_data12 <- data.frame(player12, points12, playoffs12, division12, conference12)
colnames(playoff_data12) <- c('Player', 'Points', 'Playoffs', 'Division', 'Conference')

player13 <- c('Alex Ovechkin', 'Sidney Crosby', 'John Tavares', 'Johnathan Toews', 'Patrick Kane')
points13 <- c(56, 56, 47, 48, 55)
playoffs13 <- c('Yes', 'Yes', 'Yes', 'Yes', 'Yes')
division13 <- c(1, 1, 3, 1, 1)
conference13 <- c(3, 1, 8, 1, 1)
playoff_data13 <- data.frame(player13, points13, playoffs13, division13, conference13)
colnames(playoff_data13) <- c('Player', 'Points', 'Playoffs', 'Division', 'Conference')

player14 <- c('Sidney Crosby', 'Ryan Getzlaf', 'Claude Giroux', 'Patrice Bergeron', 'Tyler Seguin')
points14 <- c(104, 87, 86, 62, 84)
playoffs14 <- c('Yes', 'Yes', 'Yes', 'Yes', 'Yes')
division14 <- c(1, 1, 3, 1, 5)
wildcard14 <- c('No', 'No', 'No', 'No', 'Yes')
playoff_data14 <- data.frame(player14, points14, playoffs14, division14, wildcard14)
colnames(playoff_data14) <- c('Player', 'Points', 'Playoffs', 'Division', 'Wildcard')

player15 <- c('Alex Ovechkin', 'John Tavares', 'Sidney Crosby', 'Ryan Getzlaf', 'Rick Nash')
points15 <- c(81, 86, 84, 70, 69)
playoffs15 <- c('Yes', 'Yes', 'Yes', 'Yes', 'Yes')
division15 <- c(2, 3, 4, 1, 1)
wildcard15 <- c('No', 'No', 'Yes', 'No', 'No')
playoff_data15 <- data.frame(player15, points15, playoffs15, division15, wildcard15)
colnames(playoff_data15) <- c('Player', 'Points', 'Playoffs', 'Division', 'Wildcard')

player16 <- c('Patrick Kane', 'Sidney Crosby', 'Jamie Benn', 'Joe Thornton', 'Alex Ovechkin')
points16 <- c(106, 85, 89, 82, 71)
playoffs16 <- c('Yes', 'Yes', 'Yes', 'Yes', 'Yes')
division16 <- c(3, 2, 1, 3, 1)
wildcard16 <- c('No', 'No', 'No', 'No', 'No')
playoff_data16 <- data.frame(player16, points16, playoffs16, division16, wildcard16)
colnames(playoff_data16) <- c('Player', 'Points', 'Playoffs', 'Division', 'Wildcard')

player17 <- c('Connor McDavid', 'Sidney Crosby', 'Brent Burns', 'Erik Karlsson', 'Patrick Kane')
points17 <- c(100, 89, 76, 71, 89)
playoffs17 <- c('Yes', 'Yes', 'Yes', 'Yes', 'Yes')
division17 <- c(2, 2, 3, 2, 1)
wildcard17 <- c('No', 'No', 'No', 'No', 'No')
playoff_data17 <- data.frame(player17, points17, playoffs17, division17, wildcard17)
colnames(playoff_data17) <- c('Player', 'Points', 'Playoffs', 'Division', 'Wildcard')

player18 <- c('Taylor Hall', 'Nathan MacKinnon', 'Anze Kopitar', 'Claude Giroux', 'Connor McDavid')
points18 <- c(93, 97, 92, 102, 108)
playoffs18 <- c('Yes', 'Yes', 'Yes', 'Yes', 'No')
division18 <- c(5, 4, 4, 3, 6)
wildcard18 <- c('Yes', 'Yes', 'Yes', 'No', 'No')
playoff_data18 <- data.frame(player18, points18, playoffs18, division18, wildcard18)
colnames(playoff_data18) <- c('Player', 'Points', 'Playoffs', 'Division', 'Wildcard')

player19 <- c('Nikita Kucherov', 'Sidney Crosby', 'Connor McDavid', 'Johnny Gaudreau', 'Brad Marchand')
points19 <- c(128, 100, 116, 99, 100)
playoffs19 <- c('Yes', 'Yes', 'No', 'Yes', 'Yes')
division19 <- c(1, 3, 7, 1, 2)
wildcard19 <- c('No', 'No', 'No', 'No', 'No')
playoff_data19 <- data.frame(player19, points19, playoffs19, division19, wildcard19)
colnames(playoff_data19) <- c('Player', 'Points', 'Playoffs', 'Division', 'Wildcard')

player20 <- c('Leon Draisaitl', 'Nathan MacKinnon', 'Artemi Panarin', 'David Pastrnak', 'Connor McDavid')
points20 <- c(110, 93, 95, 95, 97)
playoffs20 <- c('Yes', 'Yes', 'Yes', 'Yes', 'Yes')
division20 <- c(2, 2, 7, 1, 2)
wildcard20 <- c('No', 'No', 'Yes', 'No', 'No')
playoff_data20 <- data.frame(player20, points20, playoffs20, division20, wildcard20)
colnames(playoff_data20) <- c('Player', 'Points', 'Playoffs', 'Division', 'Wildcard')

player21 <- c('Connor McDavid', 'Auston Matthews', 'Nathan MacKinnon', 'Sidney Crosby', 'Brad Marchand')
points21 <- c(105, 66, 65, 62, 69)
playoffs21 <- c('Yes', 'Yes', 'Yes', 'Yes', 'Yes')
division21 <- c(2, 1, 1, 1, 3)
playoff_data21 <- data.frame(player21, points21, playoffs21, division21)
colnames(playoff_data21) <- c('Player', 'Points', 'Playoffs', 'Division')

player22 <- c('Auston Matthews', 'Connor McDavid', 'Johnny Gaudreau', 'Johnathan Huberdeau', 'Roman Josi')
points22 <- c(106, 123, 115, 115, 96)
playoffs22 <- c('Yes', 'Yes', 'Yes', 'Yes', 'Yes')
division22 <- c(2, 2, 1, 1, 5)
wildcard22 <- c('No', 'No', 'No', 'No', 'Yes')
playoff_data22 <- data.frame(player22, points22, playoffs22, division22, wildcard22)
colnames(playoff_data22) <- c('Player', 'Points', 'Playoffs', 'Division', 'Wildcard')
